name: Type Checking

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install all dependencies
        uses: Borales/actions-yarn@v2.3.0

      - name: Run type checking server
        run: cd packages/server && yarn tsc

      - name: Run type checking web
        run: cd packages/web && yarn tsc
